export const experienceMarks = [
  { value: 0, label: "0" },
  { value: 5, label: "5" },
  { value: 10, label: "10" },
  { value: 15, label: "15" },
  { value: 20, label: "20+" },
];

export const salaryMarks = [
  { value: 0, label: "0" },
  { value: 50, label: "2" },
  { value: 100, label: "5" },
  { value: 150, label: "10" },
  { value: 200, label: "20+" },
];

export const companies = [
  "Adani Group",
  "Asian Paints",
  "Axis Bank",
  "Bajaj Auto",
  "Bharat Petroleum Corporation (BPCL)",
  "Bharti Airtel",
  "Britannia Industries",
  "Cipla",
  "Coal India",
  "Dr. Reddy's Laboratories",
  "HCL Technologies",
  "HDFC Bank",
  "Hero MotoCorp",
  "Hindalco Industries",
  "Hindustan Unilever",
  "ICICI Bank",
  "Indian Oil Corporation (IOCL)",
  "IndusInd Bank",
  "Infosys",
  "ITC",
  "3M Company",
  "AbbVie",
  "Accenture plc",
  "Adobe",
  "Alibaba Group Holding Ltd.",
  "Alphabet (Google)",
  "Amazon.com",
  "Apple",
  "AstraZeneca PLC",
  "AT&T",
  "Bank of America Corporation",
  "Berkshire Hathaway",
  "BHP Group",
  "Caterpillar",
  "Chevron Corporation",
  "Cisco Systems",
  "Coca-Cola Company",
  "Comcast Corporation",
  "Exxon Mobil Corporation",
  "Facebook",
  "Ford Motor Company",
  "General Electric Company",
  "Goldman Sachs Group",
  "Honda Motor Co. Ltd.",
  "Home Depot",
  "IBM Corporation",
  "Intel Corporation",
  "Johnson & Johnson",
  "JPMorgan Chase & Co.",
  "L'Oréal S.A.",
  "Lockheed Martin Corporation",
  "Mastercard Incorporated",
  "McDonald's Corporation",
  "Merck & Co.",
  "Microsoft Corporation",
  "Netflix,",
  "Novartis AG",
  "NVIDIA Corporation",
  "Oracle Corporation",
  "PepsiCo",
  "Philip Morris International",
  "Procter & Gamble Co.",
  "Roche Holding AG",
  "Royal Dutch Shell plc",
  "Salesforce.com",
  "Samsung Electronics Co. Ltd.",
  "Sony Group Corporation",
  "Taiwan Semiconductor Manufacturing Co. Ltd.",
  "Target Corporation",
  "Tencent Holdings Ltd.",
  "Tesla",
  "The Boeing Company",
  "Twitter,",
  "Union Pacific Corporation",
  "UnitedHealth Group",
  "Verizon Communications",
  "Visa",
  "Walt Disney Company",
  "Walmart",
];

export const positions = [
  "Software Engineer",
  "Product Manager",
  "Data Scientist",
  "UI/UX Designer",
  "QA Engineer",
  "DevOps Engineer",
  "Technical Support Engineer",
  "Systems Analyst",
  "Database Administrator",
  "Network Engineer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Mobile App Developer",
  "Embedded Software Engineer",
  "Game Developer",
  "Web Developer",
  "Cloud Engineer",
  "AI/ML Engineer",
  "Software Architect",
  "Release Engineer",
  "Security Engineer",
  "Automation Engineer",
  "Integration Engineer",
  "Scrum Master",
  "Technical Lead",
  "UI/UX Developer",
  "Software Development Manager",
  "Firmware Engineer",
  "Platform Engineer",
];

export const locations = [
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Mumbai",
  "Gurgaon",
  "Noida",
  "Delhi",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Chandigarh",
  "Kochi",
  "Indore",
  "Lucknow",
  "Coimbatore",
  "Visakhapatnam",
  "Nagpur",
  "Vadodara",
  "Bhopal",
  "Patna",
  "Surat",
  "Bhubaneswar",
  "Guwahati",
  "Thiruvananthapuram",
  "Mysore",
  "Dehradun",
  "Shimla",
  "Ranchi",
  "Raipur",
  "San Francisco",
  "Seattle",
  "New York City",
  "London",
  "Tokyo",
  "Singapore",
  "Berlin",
  "Bangalore",
  "San Jose",
  "Austin",
  "Boston",
  "Toronto",
  "Dublin",
  "Sydney",
  "Tel Aviv",
  "Seattle",
  "Shanghai",
  "Seoul",
  "São Paulo",
  "Moscow",
  "Zurich",
  "Stockholm",
  "Dubai",
  "Hong Kong",
  "Paris",
  "Barcelona",
];

export const typesOfEmployment = [
  "Full-Time ",
  "Part-Time ",
  "Temporary ",
  "Contract ",
  "Freelance ",
  "Internship",
  "Seasonal ",
  "Casual ",
  "Gig ",
  "Remote ",
];

export const Data = {
  job_id: "123456",
  title: "Senior Software Engineer",
  company: {
    name: "Tech Solutions Inc.",
    location: "San Francisco, CA",
    logo: "https://humancapitalonline.com/uploads/page_img/tcs.jpg",
    size: "201-500 employees",
    website: "https://www.techsolutions.com",
  },
  posted_date: "2024-05-30",
  mode: "on-site",
  experience: "4-5 years",
  salary_range: "$120,000 - $150,000 per year",
  description:
    "We are looking for a highly skilled Senior Software Engineer to join our dynamic and innovative team. The ideal candidate will have a strong background in software development, excellent problem-solving skills, and a passion for technology.",
  responsibilities: [
    "Design, develop, and maintain software applications",
    "Collaborate with cross-functional teams to define, design, and ship new features",
    "Write clean, maintainable, and efficient code",
    "Conduct code reviews and provide constructive feedback",
    "Troubleshoot, debug, and upgrade existing software",
    "Participate in agile development processes",
  ],
  requirements: [
    "Bachelor’s degree in Computer Science, Engineering, or related field",
    "5+ years of experience in software development",
    "Proficiency in at least one modern programming language such as Java, C#, Python, or JavaScript",
    "Experience with front-end frameworks such as React or Angular",
    "Strong understanding of algorithms and data structures",
    "Excellent problem-solving and communication skills",
    "Experience with version control systems such as Git",
  ],
  technologies_used: [
    "JavaScript",
    "React",
    "Node.js",
    "Python",
    "Django",
    "AWS",
    "Docker",
    "Kubernetes",
  ],
  benefits: [
    "Competitive salary and performance bonuses",
    "Health, dental, and vision insurance",
    "401(k) with company match",
    "Flexible working hours and remote work options",
    "Generous paid time off and holidays",
    "Professional development opportunities",
    "Employee wellness programs",
    "Gym membership discounts",
    "Free snacks and beverages",
  ],
  interview_process: [
    "Initial phone screen with HR",
    "Technical interview with team lead",
    "Coding challenge",
    "On-site interview with the engineering team",
    "Final interview with the CTO",
  ],
  application_details: {
    contact_email: "hr@techsolutions.com",
    additional_instructions:
      "Please submit your resume and a cover letter outlining your qualifications and experience. Include links to your GitHub profile or any relevant projects.",
  },
};
